version: 2

sources:
  - name: tpch
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: region
        columns:
          - name: r_regionkey
            tests:
              - not_null 
              - relationships:
                  to: source('tpch', 'nation')
                  field: n_regionkey
      - name: partsupp
        columns:
          - name: ps_partkey
            tests:
              - not_null  

      - name: lineitem
        columns:
          - name: l_orderkey
            tests:
              - not_null  
      - name: orders
        columns:
          - name: o_orderkey
            tests:
              - relationships:
                  to: source('tpch', 'lineitem')
                  field: l_orderkey
      - name: nation
        columns:
          - name: n_regionkey
            tests:
              - not_null  
      - name: customer


